# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Grand Canyon Headquarters 
email: info@grandcanyonhq.com
phone: +1 (470) 910-6657
description: >- # this means to ignore newlines until "baseurl:"
  Experience the Grand Canyon like never before. Immerse yourself in our unique off-grid retreat, where 80 acres of wilderness merges life's basic comforts with an eco-conscious ethos.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://grandcanyonhq.com # the base hostname & protocol for your site, e.g. http://example.com
domain: https://grandcanyonhq.com
# twitter_username: jekyllrb
# github_username:  jekyll


permalink: /:categories/:year/:month/:day/:title

# Build settings
# theme: minima
plugins:
  - jekyll-postcss
  - jekyll-responsive-image
  - jekyll-sitemap

postcss:
  cache: false

# https://support.squarespace.com/hc/en-us/articles/206542517-Formatting-your-images-for-display-on-the-web#toc-how-do-my-images-resize-for-different-devices-
responsive_image:
  template: _includes/responsive-image.html
  default_quality: 60 
  strip: true
  base_path: assets/img
  output_path_format: assets/imgs/%{dirname}/%{filename}-%{width}w.%{extension}
  sizes:
    - width: 100
      quality: 90
    - width: 300
      quality: 80 
    - width: 500
      quality: 75
    - width: 750
    - width: 1000
    - width: 1500
    - width: 2500

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - docs
  - _site
  - yarn.lock
  - tailwind.config.js
  - postcss.config.js
  - package.json
  - Makefile
  - README.md
  - vercel.json
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
  # - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

resnexus_booking_link: https://resnexus.com/resnexus/reservations/book/879232F3-9986-4AFF-A3FC-2528F66B3EF9

faq:
  - q: What is a casita? 
    a: Our casitas are tiny homes; the structures are built as duplexes with a shared wall. Each casita measures 320 sq. ft. (30„é°) and is named after a Classic Rock album.

  - q: When can I check-in?
    a: Please check in between 3pm and 7pm. We strongly suggest arriving before sunset. If you plan to arrive after sunset, please contact us at +1 (470) 910-6657.

  - q: When is check-out?
    a: Check out is at 10am.

  - q: Do I need a 4-wheel drive vehicle?
    a: Yes, given our off-grid location, please anticipate using a 4WD vehicle or one with high clearance. The conditions of our roads vary depending on the rainy season. We are happy to meet you at HWY 64N if you would like us to accompany you to the Ranch.

  - q: Where should I park?
    a: There is a designated parking area next to the Commons.

  - q: Can I bring my pet?
    a: Two of the four Casitas are pet-friendly.  Pets require pre-approval, and owners are subject to an additional cleaning fee.

  - q: This is my first time going off-grid. How are basic utilities handled?
    a: Our electricity is supplied by a solar system (with a back-up generator for emergencies); all water is trucked in; the main source of heat is a wood burning stove; and wastewater is treated by a septic system. 

  - q: Do I need to be mindful of water consumption?
    a: Each casita has 80 gallons of water per day. This allows for approximately two 10 minute showers each day. If you will need additional water, please let us know so that we may make arrangements for a water delivery. 

  - q: I don't know how to use a wood burning stove. What should I do?
    a: Should you need assistance with the wood burning stove, we are happy to help.

  - q: May I bring electrical appliances?
    a: Electrical appliances put a strain on our solar power system, so please leave hair dryers, curling irons, electric razors and other electrical appliances at home. Also, cell phones and computers should be charged during the day if possible. 

  - q: Can I cook in the casita?
    a: Each casita kitchenette has a mini fridge and small gas range so that you may prepare simple meals. We are a BYOB facility. We provide two ice trays in your freezer, additional ice is available for purchase at the local gas station. In the Commons area, there is a canteen with cold beverages, coffee, and tea.

  - q: Are there grocery stores near by?
    a: The nearest grocery stores are 30 minutes away and are located in Williams, Tusayan, and Grand Canyon Village. There are a variety of options in Flagstaff, including a Whole Foods and Safeway.
